from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session, joinedload
from sqlalchemy import func
from src.models.db import get_db
from src.models.order_model import Order
from src.auth.role_guard import get_current_user_role
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import io
from datetime import datetime

router = APIRouter(prefix="/api/reports", tags=["Reports"])

@router.get("/sales")
def generate_sales_report(db: Session = Depends(get_db), role: str = Depends(get_current_user_role)):
    if role != "ADMIN":
        raise HTTPException(status_code=403, detail="Not authorized")

    # 1. Fetch Data WITH Part Name (Using joinedload to be efficient)
    orders = db.query(Order).options(joinedload(Order.part)).all()
    total_revenue = db.query(func.sum(Order.total_price)).scalar() or 0

    # 2. Create PDF Buffer
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    
    # 3. Draw Header
    c.setFont("Helvetica-Bold", 20)
    c.drawString(30, 750, "IMS - Monthly Sales Report")
    
    c.setFont("Helvetica", 12)
    c.drawString(30, 730, f"Generated On: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    c.drawString(30, 715, f"Generated By: Administrator")
    
    c.line(30, 700, 580, 700) # Horizontal Line (Wider)

    # 4. Draw Table Header (Adjusted spacing for Names)
    y = 670
    c.setFont("Helvetica-Bold", 10)
    c.drawString(30, y, "ID")
    c.drawString(80, y, "Part Name")        # <--- CHANGED FROM ID TO NAME
    c.drawString(280, y, "Qty")
    c.drawString(350, y, "Total (KES)")
    c.drawString(480, y, "Date")
    
    y -= 20
    c.setFont("Helvetica", 10)

    # 5. Loop Data
    for order in orders:
        if y < 50: # New Page if full
            c.showPage()
            y = 750
        
        # Get Name safely (in case part was deleted, though unlikely)
        part_name = order.part.name if order.part else f"Part #{order.part_id}"
            
        c.drawString(30, y, str(order.id))
        c.drawString(80, y, part_name[:35]) # Limit length so it doesn't overlap
        c.drawString(280, y, str(order.quantity))
        c.drawString(350, y, f"{order.total_price:,.2f}")
        c.drawString(480, y, order.created_at.strftime("%Y-%m-%d"))
        y -= 20

    # 6. Footer Totals
    c.line(30, y-10, 580, y-10)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(350, y-40, f"TOTAL: KES {total_revenue:,.2f}")

    c.save()
    buffer.seek(0)
    
    return StreamingResponse(buffer, media_type="application/pdf", headers={"Content-Disposition": "attachment; filename=sales_report.pdf"})
